### ISSUE TITLE
Add listings

### ISSUE THREAD

**Issue by rocks860** [mustafaynk/shoearstore#1]
Is there an admin panel to add items?

**Comment by rocks860** [comment]
Got it

**Comment by mustafaynk** [comment]
We developed the PHP Admin panel, but this repo is an Android app. So, I didn't add PHP admin panel. Maybe one day. Thanks for your interest.

**Comment by abhi19sept** [comment]
Please provide me code of PHP Admin Panel, my email is abhi.lohit@gmail.com
